"""add job description domain tables

Revision ID: 7e8648aadd9d
Revises: 251decd5085c
Create Date: 2026-08-31 11:04:47.541247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8648aadd9d'
down_revision: Union[str, Sequence[str], None] = '251decd5085c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'EXTRACTED', 'NEEDS_REVIEW', 'VERIFIED', name='jobdescriptionstatus'), nullable=False),
    sa.Column('raw_ai_response', sa.Text(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jd_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_description_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_type', sa.Enum('REQUIRED_SKILL', 'PREFERRED_SKILL', 'TECHNOLOGY', 'RESPONSIBILITY', 'EDUCATION', 'EXPERIENCE', 'DOMAIN', 'KEYWORD', 'SOFT_SKILL', name='requirementtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('importance', sa.Enum('REQUIRED', 'PREFERRED', 'NICE_TO_HAVE', name='importance'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jd_requirements')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
