"""add analysis and skill match tables

Revision ID: fa49a8b23b36
Revises: 7e8648aadd9d
Create Date: 2026-09-06 14:56:11.991892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa49a8b23b36'
down_revision: Union[str, Sequence[str], None] = '7e8648aadd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('job_description_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('required_skills_score', sa.Float(), nullable=False),
    sa.Column('responsibilities_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('preferred_skills_score', sa.Float(), nullable=False),
    sa.Column('keywords_score', sa.Float(), nullable=False),
    sa.Column('weights_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('jd_requirement_id', sa.String(length=36), nullable=False),
    sa.Column('resume_skill_id', sa.String(length=36), nullable=True),
    sa.Column('matched_resume_label', sa.String(length=255), nullable=True),
    sa.Column('matched_resume_text', sa.Text(), nullable=True),
    sa.Column('match_type', sa.Enum('EXACT', 'NORMALIZED', 'RELATED', 'PARTIAL', 'MISSING', 'UNKNOWN', name='matchtype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('requirement_name', sa.String(length=255), nullable=False),
    sa.Column('scoring_category', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jd_requirement_id'], ['jd_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_skill_id'], ['skills.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_matches')
    op.drop_table('analyses')
    # ### end Alembic commands ###
